#!/usr/bin/env bash
# Wire cc-tailsync's CCTailsync Swift package into a cc-ios checkout, enabling wireless save sync.
#
# WHAT IT DOES (idempotent)
#   1. Adds the CCTailsync SwiftPM package to cc-ios's app/project.yml:
#        packages: CCTailsync (local path by default, or a remote branch/version), and a
#        `- package: CCTailsync` dependency on the cc-ios app target.
#   2. Replaces cc-ios's app/Sources/SaveSyncBootstrap.swift with a version that imports CCTailsync,
#        conforms TailscaleSyncClient to cc-ios's SaveSyncProvider, and registers it in
#        SaveSync.provider (using the app's Documents/cc.save).
#   3. Runs `xcodegen generate` so the .xcodeproj picks up the package (unless --no-generate).
#
# cc-ios builds fine WITHOUT this (the standalone SaveSyncBootstrap is a no-op). Run with --remove
# to restore that standalone state.
#
# Usage:
#   tools/integrate-ios.sh --ios-repo /path/to/cc-ios
#   tools/integrate-ios.sh --ios-repo /path/to/cc-ios --remote            # use github branch main
#   tools/integrate-ios.sh --ios-repo /path/to/cc-ios --remote --version 0.1.0
#   tools/integrate-ios.sh --ios-repo /path/to/cc-ios --no-generate
#   tools/integrate-ios.sh --ios-repo /path/to/cc-ios --remove
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # the cc-tailsync checkout
ios_repo=""
mode_remote=0
branch="main"
version=""
do_generate=1
do_remove=0
provider="github"   # which save-sync client to wire: github (default) | tailscale

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ios-repo)    ios_repo="$2"; shift 2;;
    --remote)      mode_remote=1; shift;;
    --branch)      mode_remote=1; branch="$2"; shift 2;;
    --version)     mode_remote=1; version="$2"; shift 2;;
    --provider)    provider="$2"; shift 2;;
    --no-generate) do_generate=0; shift;;
    --remove)      do_remove=1; shift;;
    -h|--help)     grep '^#' "$0" | grep -v '^#!' | sed 's/^# \{0,1\}//'; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

case "$provider" in
  github|tailscale) ;;
  *) echo "error: --provider must be 'github' or 'tailscale' (got '$provider')" >&2; exit 2;;
esac

[[ -n "$ios_repo" ]] || { echo "error: pass --ios-repo /path/to/cc-ios" >&2; exit 2; }
ios_repo="$(cd "$ios_repo" && pwd)"
project_yml="$ios_repo/app/project.yml"
bootstrap="$ios_repo/app/Sources/SaveSyncBootstrap.swift"
[[ -f "$project_yml" ]] || { echo "error: $project_yml not found (is --ios-repo a cc-ios checkout?)" >&2; exit 1; }
[[ -f "$bootstrap"   ]] || { echo "error: $bootstrap not found (expected the cc-ios save-sync seam)" >&2; exit 1; }

write_standalone_bootstrap() {
  cat > "$bootstrap" <<'SWIFT'
import Foundation

/// Installs the optional network save-sync provider, if one is available.
///
/// **This is the STANDALONE (no-op) version.** cc-ios persists saves to a file on its own
/// (`SaveBridge` + `SaveFolder`) and needs no network, so nothing is registered and
/// `SaveSync.provider` stays `nil` — every sync call in `GameView` becomes a silent no-op.
///
/// Enabling wireless (Tailscale) sync is a single opt-in step:
/// **[cc-tailsync](https://github.com/cc-mods/cc-tailsync)**'s `tools/integrate-ios.sh` adds the
/// `CCTailsync` Swift package to the Xcode project and **replaces this file** with a version that
/// imports `CCTailsync`, conforms its `TailscaleSyncClient` to `SaveSyncProvider`, and registers it
/// in `SaveSync.provider`. Re-run that script to (re)enable sync; restoring this file disables it.
///
/// Keeping the wiring behind one well-known function (called from `CCIOSApp.init`) is what lets
/// cc-ios build with zero reference to cc-tailsync symbols when the package isn't linked.
enum SaveSyncBootstrap {
    static func installIfAvailable() {
        // No-op: file-based save persistence only.
        // Add wireless sync with cc-tailsync: https://github.com/cc-mods/cc-tailsync
    }
}
SWIFT
}

write_wired_bootstrap() {
  if [[ "$provider" == "github" ]]; then
    cat > "$bootstrap" <<'SWIFT'
import Foundation
import CCTailsync

// ⚠️ GENERATED by cc-tailsync/tools/integrate-ios.sh — do not edit by hand.
// Restore the standalone no-op with: tools/integrate-ios.sh --ios-repo <this repo> --remove
//
// Wires cc-tailsync's GitHubSaveSyncClient (the always-online, content-SHA, versioned hub) into
// cc-ios's SaveSync seam: as the launch/push provider AND the consent-pull provider (the "newer
// save detected — load? Y/N" prompt). Dormant until Documents/cc-github.json (a fine-grained PAT)
// exists — without it every call is a silent no-op, so the app still runs fully standalone.
extension GitHubSaveSyncClient: SaveSyncProvider {}
extension GitHubSaveSyncClient: ConsentPullProvider {}

enum SaveSyncBootstrap {
    static func installIfAvailable() {
        // Sync the same Documents/cc.save the app persists; config is Documents/cc-github.json.
        let client = GitHubSaveSyncClient(saveFileURL: SaveBridge.saveFileURL)
        SaveSync.provider = client
        SaveSync.consentProvider = client
    }
}
SWIFT
  else
    cat > "$bootstrap" <<'SWIFT'
import Foundation
import CCTailsync

// ⚠️ GENERATED by cc-tailsync/tools/integrate-ios.sh --provider tailscale — do not edit by hand.
// Restore the standalone no-op with: tools/integrate-ios.sh --ios-repo <this repo> --remove
//
// Conforms cc-tailsync's TailscaleSyncClient to cc-ios's SaveSyncProvider seam (cc-ios owns the
// protocol; the method signatures match) and registers it as the process-wide sync provider.
// (Legacy transport — prefer --provider github: always-online, content-SHA, versioned, consent pull.)
extension TailscaleSyncClient: SaveSyncProvider {}

enum SaveSyncBootstrap {
    static func installIfAvailable() {
        // Bridge into the same Documents/cc.save the app persists; config is Documents/cc-sync.json.
        SaveSync.provider = TailscaleSyncClient(saveFileURL: SaveBridge.saveFileURL)
    }
}
SWIFT
  fi
}

edit_project_yml() {  # $1 = add|remove ; reads PKG_BLOCK from env for add
  PKG_BLOCK="${PKG_BLOCK:-}" python3 - "$project_yml" "$1" <<'PY'
import os, re, sys
path, action = sys.argv[1], sys.argv[2]
s = open(path, encoding="utf-8").read()

DEP_BLOCK = ("    dependencies:\n"
             "      - package: CCTailsync\n"
             "        product: CCTailsync\n")

if action == "add":
    if "CCTailsync" in s:
        print("  project.yml already references CCTailsync — leaving as is.")
        sys.exit(0)
    pkg_block = os.environ.get("PKG_BLOCK", "")
    s2, n1 = re.subn(r"(?m)^targets:\n", pkg_block + "targets:\n", s, count=1)
    if n1 != 1:
        sys.exit("ERROR: could not find a top-level 'targets:' line in project.yml")
    s3, n2 = re.subn(r"(?m)^    type: application\n",
                     "    type: application\n" + DEP_BLOCK, s2, count=1)
    if n2 != 1:
        sys.exit("ERROR: could not find the app target's 'type: application' line")
    open(path, "w", encoding="utf-8").write(s3)
    print("  + CCTailsync package + app-target dependency added to project.yml")
else:  # remove
    if "CCTailsync" not in s:
        print("  project.yml has no CCTailsync reference — nothing to remove.")
        sys.exit(0)
    # Strip the dependency block.
    s = s.replace(DEP_BLOCK, "")
    # Strip the top-level packages block we inserted (packages: \n  CCTailsync: \n <indented...>).
    s = re.sub(r"(?m)^packages:\n  CCTailsync:\n(?:    .*\n)+\n?", "", s, count=1)
    # If a packages: block remains with CCTailsync only via a different shape, fall back to a
    # line-wise scrub of any stray CCTailsync lines.
    if "CCTailsync" in s:
        s = "\n".join(l for l in s.splitlines() if "CCTailsync" not in l) + "\n"
    open(path, "w", encoding="utf-8").write(s)
    print("  - CCTailsync removed from project.yml")
PY
}

if [[ "$do_remove" -eq 1 ]]; then
  echo "Removing cc-tailsync integration from $ios_repo …"
  edit_project_yml remove
  write_standalone_bootstrap
  echo "  restored standalone (no-op) SaveSyncBootstrap.swift"
else
  echo "Integrating cc-tailsync into $ios_repo …"
  if [[ "$mode_remote" -eq 1 ]]; then
    if [[ -n "$version" ]]; then
      PKG_BLOCK=$'packages:\n  CCTailsync:\n    url: https://github.com/cc-mods/cc-tailsync.git\n    from: '"$version"$'\n\n'
      echo "  package: github cc-mods/cc-tailsync (from: $version)"
    else
      PKG_BLOCK=$'packages:\n  CCTailsync:\n    url: https://github.com/cc-mods/cc-tailsync.git\n    branch: '"$branch"$'\n\n'
      echo "  package: github cc-mods/cc-tailsync (branch: $branch)"
    fi
  else
    # Local package: write a RELATIVE path (from app/ to the cc-tailsync repo) so project.yml never
    # embeds a machine-specific absolute path like /Users/<name>/… — which must never be committed.
    # xcodegen resolves package paths relative to the spec directory (app/).
    rel_root="$(python3 -c 'import os,sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))' "$repo_root" "$ios_repo/app")"
    PKG_BLOCK=$'packages:\n  CCTailsync:\n    path: '"$rel_root"$'\n\n'
    echo "  package: local path $rel_root (relative to app/)"
  fi
  export PKG_BLOCK
  edit_project_yml add
  write_wired_bootstrap
  echo "  wrote wired SaveSyncBootstrap.swift (registers TailscaleSyncClient)"
fi

# Regenerate the Xcode project so the package change takes effect.
if [[ "$do_generate" -eq 1 ]]; then
  if command -v xcodegen >/dev/null 2>&1; then
    ( cd "$ios_repo/app" && xcodegen generate ) && echo "Ran xcodegen generate."
  else
    echo "note: xcodegen not found — run it yourself:  ( cd \"$ios_repo/app\" && xcodegen generate )" >&2
  fi
else
  echo "Skipped xcodegen (--no-generate). Run:  ( cd \"$ios_repo/app\" && xcodegen generate )"
fi

echo "Done. Build cc-ios; then configure a server with tools/setup-sync.sh (see docs/iOS.md)."
